<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>OpenAI.CodexSdk.Maf</RootNamespace>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
	<None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
  	<PackageReference Include="Microsoft.Agents.AI" />
  	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\CodexSdk\CodexSdk.csproj" />
  </ItemGroup>

</Project>
